## Task 1
**Why is it appropriate to use the binomial distribution?** 
Because the poll data is binomial. 

In [48]:
import scipy.stats as sts
import numpy as np

# setting sample size
sample_size = 1000
p = 0.1
# q as 1 - p
q = 0.9

# calculating mean, standard deviation
mean = sample_size * p
std = np.sqrt(q*mean)

In [49]:
# calculating lower and upper bound of confidence interval
# formula mean +- 2*std
# in any distribution about 95% of values will be within 2 STDs of the mean

lower_bound = mean - 2*std
upper_bound = mean + 2*std

print("95% Confidence Interval is:", [lower_bound, upper_bound])

95% Confidence Interval is: [81.02633403898972, 118.97366596101028]


In [56]:
# calculating the percentage outcome
percentage_outcome = round((1.96*std)/sample_size, 3)

print('The percentage outcome is:', percentage_outcome*100, "%")

The percentage outcome is: 1.9 %


## Task 2

In [37]:
def matrix_replicate(empty_matrix, samples, percentages, round_value):
    # running for loops in range of 9, 5, to go through the matrix
    for sample_size_i in range(9):
        for percentage_i in range(5):
            # sample size
            n = samples[percentage_i]
            # p
            p = percentages[sample_size_i]
            #q as 1-p
            q = 1 - p
            
            #mean
            mean = n*p
            #standard deviation
            std = np.sqrt(q*mean)
            
            #filling out matrix as we run the loops
            empty_matrix[sample_size_i, percentage_i] = round((2*std)/n, round_value)*100
    
    return empty_matrix

In [38]:
samples = [1000, 750, 500, 250, 100]
percentages = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
empty_matrix = np.zeros([9, 5])
print(empty_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
## replicating the table, using round() with 2 
matrix_replicate(empty_matrix, samples, percentages, 2)

array([[ 2.,  2.,  3.,  4.,  6.],
       [ 3.,  3.,  4.,  5.,  8.],
       [ 3.,  3.,  4.,  6.,  9.],
       [ 3.,  4.,  4.,  6., 10.],
       [ 3.,  4.,  4.,  6., 10.],
       [ 3.,  4.,  4.,  6., 10.],
       [ 3.,  3.,  4.,  6.,  9.],
       [ 3.,  3.,  4.,  5.,  8.],
       [ 2.,  2.,  3.,  4.,  6.]])

In [46]:
## replicating the table, using round() with 3
matrix_replicate(empty_matrix, samples, percentages, 3)

array([[ 1.9,  2.2,  2.7,  3.8,  6. ],
       [ 2.5,  2.9,  3.6,  5.1,  8. ],
       [ 2.9,  3.3,  4.1,  5.8,  9.2],
       [ 3.1,  3.6,  4.4,  6.2,  9.8],
       [ 3.2,  3.7,  4.5,  6.3, 10. ],
       [ 3.1,  3.6,  4.4,  6.2,  9.8],
       [ 2.9,  3.3,  4.1,  5.8,  9.2],
       [ 2.5,  2.9,  3.6,  5.1,  8. ],
       [ 1.9,  2.2,  2.7,  3.8,  6. ]])

There is a slight difference in this table and the one in the article, and I looked into rounding the values to see if the issue comes from the way matrix values were rounded in the table.